version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db-data:
